version: "3"

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    volumes:
      - wp_volume:/var/www/html/
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - db_volume:/var/lib/mysql/
    networks:
      - bridge-network
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    volumes:
      - wp_volume:/var/www/html/
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env
    
  redis:
    container_name: redis
    depends_on:
     - wordpress
    build: ./requirements/bonus/redis/
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env

  website:
    container_name: website
    build: ./requirements/bonus/website/
    networks:
     - bridge-network
    ports:
     - "5173:5173"
    restart: always
    env_file:
     - .env

  
volumes:
  wp_volume:
    driver: local
    driver_opts:
      device: /home/kdainely/data/wordpress
      o: bind
      type: none
  db_volume:
    driver: local
    driver_opts:
      device: /home/kdainely/data/mariadb
      o: bind
      type: none

networks:
  bridge-network:
    driver: bridge
